configurations/Everest.json

The supported PSU model should be 51DA for Everest.
Change-Id: Id11f29b3a89c023eca9f1e51859d5627534149d2
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>

everest: Change PSU model from 51EA to 51DA

---

configurations/Blyth.json
configurations/Storm King.json
schemas/legacy.json

Would like to get this in downstream for fan-control testing.
This specifies the parameters for a virtual ambient temperature sensor.
phosphor-virtual-sensor will take this information and create the
virtual sensor.
The virtual sensor takes the readings of three temperature sensors
(TMP275, DPS310, SI7020) on this board to calculate the ambient
temperature. This ambient temperature is published on DBus and will be
used for fan control.
We are using a modified median to calculate this ambient temperature. In
the case of only two valid temperature readings we will use the highest
one - in case the other is too low in error. Otherwise we take the
median value.

Add Ambient Virtual Temperature Sensor

---

configurations/Ingraham.json
configurations/Tola.json
meson.build
schemas/legacy.json

Presently there is no upstream commit for this addition.
The new files support reading the on-board battery voltage
via GPIO line 42.
ON RAINIER:
Tested: busctl introspect xyz.openbmc_project.EntityManager
/xyz/openbmc_project/inventory/system/board/Ingraham_Board/Battery_Voltage
Tested: busctl introspect xyz.openbmc_project.ADCSensor
/xyz/openbmc_project/sensors/voltage/Battery_Voltage
ON EVEREST:
Tested: busctl introspect xyz.openbmc_project.EntityManager
/xyz/openbmc_project/inventory/system/board/Tola_Board/Battery_Voltage
Tested: busctl introspect xyz.openbmc_project.ADCSensor
/xyz/openbmc_project/sensors/voltage/Battery_Voltage
Signed-off-by: Tom Ippolito <thomas.ippolito@ibm.com>

New JSON file to enable ADC read of Rainier and Everest battery voltage

---

configurations/Rainier 1S4U Chassis.json
configurations/Rainier 2U Chassis.json
configurations/Rainier 4U Chassis.json
schemas/SupportedConfiguration.json

Add the PowerConfigFullLoad property as an optional property to indicate
the value that the power-config-full-load GPIO should be set to for
systems that support it.
Reference:
https://github.com/openbmc/docs/blob/master/designs/device-tree-gpio-naming.md#power-config-full-load
Change-Id: I107bbbeb147f4f23462e4b2f26adb2d51733b256
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>

Supported Configuration: Add PowerConfigFullLoad

---

configurations/Bellavista.json
configurations/Blyth.json
configurations/Nisqually.json
configurations/Storm King.json

Change the poll rates on the TMP275 temperature sensors to 1 second from the default of .5 seconds.  The poll rates of the SI7020 and DPS310 temperature sensors default to 1s already.

IBM: Change TMP275 poll rates to 1s

---

configurations/PM1735.json

These drives seem to report a temperature value of -17 until some as yet
unknown configuration is done by the host.  Until the NVME sensor code
can detect when the temperatures are valid, just remove the lower
thresholds so there are no errors created.
Change-Id: Ib679c4d4e41fe9a5a30b7be5d63ff91a68038358

Remove PM1735 lower thresholds

---

configurations/Blyth.json
configurations/Storm King.json

Add the relative humidity sensor to the Blyth and Storm King.  This
triggers the following sensor to be created:
/xyz/openbmc_project/sensors/humidity/Relative_Humidity
This is in master, though those files after other changes so I couldn't just pull over the commit.
Change-Id: I5283f5775b8ecbe3a697db4ae8084f32c8c460da

Add relative humidity sensor to 2 IBM cards

---

configurations/Everest.json
configurations/Rainier 1S4U Chassis.json
configurations/Rainier 2U Chassis.json
configurations/Rainier 4U Chassis.json
schemas/IBM.json
schemas/global.json

Add PowerModeProperties schema to define the factory default power mode
properties of a system:
- Power Mode
- Idle Power Saver Parameters
All of these parameters are part of the version 2021.2 Redfish Schema
Supplement under the ComputerSystem 1.16.0 schema:
For details on the values and descriptions, see the PowerMode and
IdlePowerSaver schemas in the Redfish documentation:
https://www.dmtf.org/sites/default/files/standards/documents/DSP0268_2021.2.pdf
These are the factory default values as defined by the system architect.
All of these parameters are system-wide parameters and are used to
define the operation of that system as it relates to power.
These are the values will be used the first time a system is powered on.
They can also be used if the customer wants to restore these …

schema: ibm: add default power mode props. schema

---

configurations/PM1735.json

The drives should be fixed now, and we were asked to put this back in to
catch the bad temp if it happens again.
This reverts commit cc21acdd26aa5fdc9a0a6f4075c3351d294eda17.
Change-Id: I3dc1c6d4553ef245dbf7b05ea022ea19d22ef3b2

Revert "Remove PM1735 lower thresholds (#13)"

---

configurations/Storm King.json

Reduce the `HardShutdown` and `SoftShutdown` thresholds by -5C, which
was determined after thermal chamber testing.
Change-Id: I5bd95b5d6bf66bed6d5e29a58f883bcd841223c1
Signed-off-by: Matthew Barth <msbarth@us.ibm.com>

configs:Storm King: Update ambient thresholds

---

configurations/Ingraham.json
configurations/Tola.json

The name agreed to was rtc-battery-voltage-read-enable.
Signed-off-by: Joel Stanley <joel@jms.id.au>

configs: Update RTC battery pin to upstream name

---

configurations/Bear Lake.json
configurations/Bear River.json
configurations/Flett.json

This commit gives the NVMe JBOF and PCIe cable card temp sensors a
stable name, so associations can be made to their corresponding D-Bus
objects in phosphor-inventory-manager (e.g.
.../motherboard/pcie_slot10/pciecard10).
The location code segment is used as the unique identifier of the sensor
names, like NVMe_JBOF_Card_C11_Temp.
The $slotnumber variable comes from the SlotNumber D-Bus property on the
inventory-manager's D-Bus object for the card.
Needs https://github.ibm.com/openbmc/openbmc/pull/1965 to merge first as that provides the SlotNumber property.
Change-Id: If98bbd5842e940fde6e3afd7f63439bc0a6dc854

configs:ibm: Rename PCIe card temp sensors

---

configurations/Blyth.json
configurations/Storm King.json

Include warning thresholds on each of the ambient sensors so that an
error is logged if a reading from each sensor is either above 100C or
below 0C.
Change-Id: I160c0291743da988a9951c902112845d9791a094
Signed-off-by: Matthew Barth <msbarth@us.ibm.com>

configs: Blyth & Storm King ambient sensor thresholds

---

src/EntityManager.cpp

The propertiesChangedCallback has a 5s idle timer. The purpose of
this timer is to prevent a flood of D-Bus signals that the callback
reacts to from causing rescans too quickly.
However, if we have rogue applications generating, for example,
an InterfacesAdded signal say every 2s, the 5s timer keeps getting
restarted, causing entity manager to never actually run the scan.
This commit adds a fail-safe that keeps us from looping in the timer
restarts forever by forcing a scan when 15s elapse. The start time to
measure these 15s is reset every time we either get a chance to scan or
when the 5s timer is not running.
Ideally, we would want to look into a design where we could be more
restrictive of the signals that entity manager responds to, but that is
probably a long-term solution.
Tested: …

entity-manager: Failsafe for scan callback timer

---

configurations/generic_nvme_drive.json
meson.build

We don't know the model of the drives exposed by platform-fru-detect, so
don't pretend we do.
Must not be merged before integration of https://github.com/ibm-openbmc/phosphor-fan-presence/pull/11 into ibm-openbmc/openbmc

configurations: Fix misleading drive model name

---

include/EntityManager.hpp
include/Utils.hpp
src/EntityManager.cpp
src/PerformScan.cpp

Allow dynamic inventory associations to be added to sensors by reactors
in the context of our Frankenstein's monster of a PIM/EM combo.
The disconnect in the EM data model between where we know about the path of
the object that triggered the probe and where we publish the probed
configuration on DBus drives some complexity in the implementation. To
bridge that gap we need to create a bit of a wormhole through the
codebase. An alternative to making a wormhole is to inject the path
metadata straight into the EM data model, but that requires more
analysis than I have time or intestinal fortitude for right now.
The wormhole we create is built on a spiritual reimplementation of
Linux's container_of() macro. By embedding the systemConfiguration in a
struct we can reach up from its pointer and …

EntityManager: Associate configs with their DBus probe source

---

configurations/Blyth.json
configurations/Storm King.json

Made a few updates related to the hysteresis values on the virtual
ambient temperature sensor on the Storm King and Blyth panels.
1) Added them to the Warning and SoftShutdown thresholds on Storm King,
where they were missing.  Used a value of 3.
2) For the HardShutdown thresholds on both Storm King and Blyth, used a
hysteresis of 50 to make it high enough to ensure the hard shutdown
isn't cancellable since it isn't built into the sensor monitor code.
In practice this probably isn't likely to matter much as the delay
before the shutdown is only 23 seconds, and also PHYP was already
told to shutdown the box after the SoftShutdown threshold was
crossed.
Change-Id: I7b21f1af2f8667e3ded4b06cffd458e8743e619d

configs:ibm: Virtual ambient hysteresis updates

---

include/EntityManager.hpp

Add the name of the inventory item into the journal messages that print when inventory adds or removes occur so that it's obvious which part is being referred to.
Journal output:
entity-manager[3395]: Inventory Added: Blyth Panel
And in the journal metadata:
NAME=Blyth Panel
This also picks up the upstream change to have these be INFO traces.
This merged upstream with 200bf40ee9f03d715500b41b6128a61991f9243e.
Change-Id: I7ce351e72831c69f3f927486350142dd466aa630

Add name to InventoryAdded/Removed journal entries

---

src/EntityManager.cpp

Unique-named dbus connections should not be exposing dbus objects and are created by dbus clients (if only an unnamed connection exists). Filter these out in order to reduce the re-scanning effort in entity-manager.
On some systems with a high number shell-script driven `busctl` operations, this was reported to have a net performance benefit.  I ran this on Bletchley hardware and observed a small (<1sec) boot time performance, which was difficult to distinguish from the noise.
Tested: Ran on Bletchley and observed identical EM `busctl tree`.
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I08b1fe87665312e9bab019f7bff748e03cdc0027

ignore unique-name dbus connections

---

configurations/Rainier 1S4U Chassis.json

Support has been added for Rainier 1s4u systems with 1000W power supplies to run with only two power supplies. Change the redundant count in this configuration to support.
Signed-off-by: Jim Wright <jlwright@us.ibm.com>

Allow 2 PS in Rainier 1s4u 1000W configuration

---

src/perform_scan.cpp

This reverts commit 8880238fe1e259f94e638a03e60788f5674f5cf2.
It was found that this was causing inventory to go missing every other restart of entity-manager. That's clearly not the intended effect, so back the change out in preparation to reconsider the approach.
Signed-off-by: Andrew Jeffery <andrew@aj.id.au>

Revert "PerformScan: Don't insert cached value for templated configs (#32)

---

src/perform_scan.cpp

We don't retain enough information to know that the cached record is valid in the context of the properties collected on the most recent scan. As such, if the config is templated, skip injecting the cached record.
Regenerating the configuration in the context of the newly gathered data prevents e.g. publishing stale I2C data gathered from xyz.openbmc_project.Inventory.Decorator.I2CDevice which is often not the interface that triggered the probe. This last fact is is important, because the record name generated by entity-manager for use in the cache lookup is only based on the information captured in the interface triggering the probe statement. Thus if a device is moved between slots the fact that we don't account for slot-specific information causes a false hit.
Change-Id: …

PerformScan: Don't insert cached value for templated configs (#32)

---

configurations/pennybacker.json

Fix the Bonnell Power Supply I2C addresses.
Change-Id: I7ae6f625c009fe0c79a8e95f33540a75f662fcee

configuration: Fix Bonnell PSU I2C addresses

---

configurations/pennybacker.json

Add the config for ADCSensor to read the RTC battery voltage on IBM's Pennybacker board.
Tested:
Sensor was on D-Bus with a value of 3.0819 Volts.
Change-Id: If468f15de2ad10fded8c1ef85bf0b2f4dd230a47

configs: Add battery config to pennybacker

---

src/entity_manager.cpp

Bugs in either an entity-manager config file or in code that hosts D-Bus properties that entity-manager probes can cause it to try to create the same object path on D-Bus twice.  When this happens, it will crash with an unhandled org.freedesktop.DBus.Error.FileExists exception when it tries to create the second xyz.openbmc_project.AddObject interface on the path.
It isn't always that easy to figure out which object path it failed on - it requires either using gdb on the core dump or looking for duplicate Name fields in /var/configuration/system.json.
This commits makes it obvious by catching the initial exception, tracing the object path in the journal, and then rethrowing.  The new trace is the first one below:
```
entity-manager[14753]: Failed creating AddObject method on …
```

Trace object path on FileExists crashes

---

configurations/blyth.json
configurations/storm_king.json

```
The hysteresis value on the hard shutdown threshold on the virtual
ambient was artificially high to prevent the hard shutdown from being
canceled by the temp going down, because it's referred to as an 'EPOW4
alert' inside IBM and that shutdown is not supposed to be canceled ever
if it gets that hot.
However the problem with such a big hysteresis is even on the next boot
when the temp is back to room temp it won't have crossed that hysteresis
value so will just shut down again.
So, just change it back to what it was previously, 3, and in a future
release I'll change the sensor monitor code to make that shutdown
uncancellable.  It's pretty unlikely the temp would drop by that much in
the 23 seconds before the hard shutdown anyway, and we'd still be in the
process of having the host shut …
```

1050: Change ambient temp hard shutdown hysteresis

---

configurations/bonnell.json
configurations/everest.json
configurations/ingraham.json
configurations/rainier_1s4u_chassis.json
configurations/rainier_2u_chassis.json
configurations/rainier_4u_chassis.json
configurations/tola.json
schemas/global.json
schemas/legacy.json
schemas/openbmc-dbus.json
src/entity_manager.cpp
src/fru_device.cpp
src/fru_utils.cpp
src/perform_probe.cpp
src/perform_scan.cpp
src/utils.cpp

Pull in the 'configs: Add Compatible iface to IBM systems' commit because there is some code that wants it in 1060.
This also pulled in the commit that added it to the schema.
The next commit was needed for some new clang-tidy checks being done in CI, which was also from master.
The last commit was just some formatting I had to fix up since CI hasn't been run for so long in EM.

Add Compatible interface to IBM chassis configs

---

configurations/generic_nvme_drive.json
src/entity_manager.cpp

Remove an EEPROM stanza that IBM doesn't use from the NVMe config file.
Also fix how the  associations interface is stored in the interface map so that it can actually be deleted when a FRU is removed.
These are only downstream problems.

EM fixes for 1110

---

src/entity_manager.cpp

This code change is related to the code review,
https://gerrit.openbmc.org/c/openbmc/phosphor-led-manager/+/66774
Where “Phosphor LED Manager” app was waiting to read interface value from DBus hosted by EntityManager to find out its system type. It caused more delay in loading appropriate system JSON file, hence “Phosphor LED Manager” app missing early faulty FRU notifications.
To fix this issue, reading system type from device tree is introduced. For this, code reviewer asked to check what was causing delay in EntityManager and asked to improve efficiency of EM if possible.
For this suggestion, tested EntityManager with varying delays in propertiesChangedCallback api, ranging from 5 seconds to 500 milliseconds on IBM systems.
Observed improved performance in creating interfaces for …

Reducing expire time in propertiesChangedCallback

---

configurations/system1_chassis.json
schemas/legacy.json

Some GPIOs do not support event_read method to monitor for value changes. Added a new MonitorType field to specify if the GPIO needs to be manually polled to detect presence.
Also added PCIE Switch temperature sensors
Tested:
- Verified no change when MonitorType not specified
- Verified functionality when Polling enum was specified
Change-Id: Ie5e8a2afe43d05192828292b629baade6b0c9c82

configuration: system1: Add GPIO monitoring type

---

configurations/generic_nvme_drive.json

Don't use $index in the D-Bus names, because EM can get confused by platform-fru-detect interactions and tries to put two instances of the same object path on D-Bus and will crash.
Instead use SlotNumber, which is a property on the xyz.openbmc_project.Inventory.Decorator.Slot interface that will be on D-Bus on the drive inventory-manager path.
Change-Id: I76b6bd5183a50a6c265bc151880c10adc7213a88

configs: Use known num in generic_nvme_drive

---

configurations/system1_chassis.json

The dual rotor fans are indexed by 1 rotor for each fan, followed by the second rotor for those fans.
Tested on system1 hw
Before:
Fan      Rotor     Present    RPM   PWM: %  Target  Zone
---     --------   -------   -----  ------  ------  ----
Fan1    Fan1a_in    true      4102   39.22   100%   0 (CECIO)
Fan1    Fan1b_in    true      4054
Fan2    Fan2a_in    true      4032   39.22   100%   0 (CECIO)
Fan2    Fan2b_in    true      4089
Fan3    Fan3a_in    true      4040   39.22   100%   0 (CECIO)
Fan3    Fan3b_in    true         0
Fan4    Fan4a_in    true         0   39.22   100%   0 (CECIO)
Fan4    Fan4b_in    true         0
Fan5    Fan5a_in    true         0   39.22   100%   0 (CECIO)
Fan5    Fan5b_in    true         0
Fan6    Fan6_in     false        0   39.22   100%   1 (NVME)
Fan7 …

configuration: system1: Fix fan indexing problem

---

configurations/system1_baseboard.json

Adding these in allows the CPU and DIMM temperatures to be collected on the BMC.
Tested:
- Confirmed we now get DIMM and Core temperatures on system1
Change-Id: Ia0578a60463b44bebbeaf74fa67f275a493bfacb

configurations: system1: add XeonCPU

---

configurations/generic_nvme_drive.json

Don't use $index in the D-Bus names, because EM can get confused by platform-fru-detect interactions and tries to put two instances of the same object path on D-Bus and will crash.
Instead use SlotNumber, which is a property on the xyz.openbmc_project.Inventory.Decorator.Slot interface that will be on D-Bus on the drive inventory-manager path.
Change-Id: I76b6bd5183a50a6c265bc151880c10adc7213a88
Change-Id: I178eab998e53e48c1d0823e262bcd3f21c0da136

configs: Use known num in generic_nvme_drive (#72)

---

configurations/system1_baseboard.json
configurations/system1_psu.json
meson.build

System1 ended up going with standard Common Redundant Power Supplies (CRPS). Add them in and create sensors for what's available.
Testing:
- Verified expected sensors were in GUI and values seemed reasonable at power off and on states
Change-Id: I1b265597ee765a79558cff05a284263fc4334738
Upstream: https://gerrit.openbmc.org/c/openbmc/entity-manager/+/75912

configurations: system1: change PSUs to CRPS

---

configurations/system1_baseboard.json
configurations/system1_chassis.json

This is the upstream version of system1_chassis.json, some of the changes were missing downstream.
Updated the system1_baseboard.json:
Modified the PowerState for the PCIE Switches and SPYRE card
thermal sensors to only be read after the host power on.
Corrected one bus number for Spyre card.
Tested on system1 hw
Change-Id: I9fe0d0c9f8f2ba615e1f1e6dbe55cb31468f3f7f

configurations: system1: update downstream system1_chassis.json

---

meson.build
meson_options.txt
src/fru_device.cpp

Our systems have lots of i2c buses and muxes. Scanning all of them is problematic, especially during power on when other applications are going out to the i2c buses (including the host firmware).
The only i2c reads we need from fru-device are during the boot to BMC Ready so disable all other i2c reads after that via a new config option.
Tested:
- Confirmed I see the new log in the journal and no i2c bus busy errors with this change during power on

fru-device: no scans on power on

---

configurations/system1_baseboard.json

The sensor numbering was backwards.
Testing on system1 hw.
Before:
PCIE_SWITCH1_TEMP     32.69   DegreesC
PCIE_SWITCH2_TEMP     31.81   DegreesC
PCIE_SWITCH3_TEMP     40.81   DegreesC
PCIE_SWITCH4_TEMP     36.75   DegreesC
PCIE_SWITCH5_TEMP     46.19   DegreesC
PCIE_SWITCH6_TEMP     40.56   DegreesC
After:
PCIE_SWITCH1_TEMP     40.56   DegreesC
PCIE_SWITCH2_TEMP     40.62   DegreesC
PCIE_SWITCH3_TEMP     32.75   DegreesC
PCIE_SWITCH4_TEMP     46.06   DegreesC
PCIE_SWITCH5_TEMP     36.81   DegreesC
PCIE_SWITCH6_TEMP     31.88   DegreesC
Change-Id: Iaedcbfde951f9a22afd10bde97c4a3c6a90c5740

configurations: system1: Correct PCI switch thermal sensors

---

configurations/balcones.json
configurations/meson.build
configurations/waterloo.json
schemas/ibm.json

Add Balcones and Waterloo configuration, Balcones IM (0x60004000) and Waterloo CCIN (2E46). The configuration files are exact same copy of Bonnell and Pennybacker
Test:
Built an image and verified balcones.json and waterloo.json exist in
the image
Change-Id: Id171c35af1f8131d937dcfaa2e37f6cdaada31fd

config: Add Balcones and Waterloo

---

configurations/blyth2.json
configurations/storm_king2.json
meson.build
test/test_fru-utils.cpp

Add configs for the Blyth2 and Storm King2, which are follow ons to the original panels, with different CCINs and an HDC1080 for the humidity/temp sensor.

Blyth2 and StormKing2 w/ HDC1080 config files

---

configurations/system1_baseboard.json

System1 should utilize the same thresholds and hysteresis ADC values as sbp1. Update to match the latest sbp1 values.
Tested:
- Put on system1 and verified expected thresholds and no errors in web
interface
Change-Id: Ie8cba2eee37dc6d856295625a6d12d512bed9053

configurations: system1: update ADC threshold and hysteresis
